export enum SocketEvent {
  ORDER_BUY_SIGNATURE = 'ORDER_BUY_SIGNATURE',
  ORDER_BUY_REQUEST = 'ORDER_BUY_REQUEST',
  ORDER_BUY_RESULT = 'ORDER_BUY_RESULT',

  ORDER_SELL_SIGNATURE = 'ORDER_SELL_SIGNATURE',
  ORDER_SELL_REQUEST = 'ORDER_SELL_REQUEST',
  ORDER_SELL_RESULT = 'ORDER_SELL_RESULT',
}
